### ISSUE TITLE
你好，有个文字想咨询下你

### ISSUE THREAD

**Issue by mashuangshuang** [ruansongsong/node-spider-of-weibo#1]
我看了下你的源代码，在数据抓取的url却不是原微博的链接，我看应该是json数据，这是异步获得嘛，谢谢啦

**Comment by ruansongsong** [comment]
对，我是通过分析直接抓取微博 json 数据接口的，通过请求这个接口的 url 就可以得到一些数据

**Comment by mashuangshuang** [comment]
ok ，非常感谢，移动端找到了接口
